---
- name: Playbook
  hosts: cicd
  tasks:
    - name: log on ECR
      shell: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 772004002961.dkr.ecr.eu-west-1.amazonaws.com
    - name: pull image
      shell: docker pull 772004002961.dkr.ecr.eu-west-1.amazonaws.com/grp-01:10
    - name: Run Docker
      shell: docker run --name=cicd_container_test -d -p 8081:8081 772004002961.dkr.ecr.eu-west-1.amazonaws.com/grp-01:10
